name: contactos_example
description: Testbed for the contactos_ios implementation.
publish_to: 'none'
version: 0.0.1


environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.29.3"


dependencies:
  flutter:
    sdk: flutter
  contactos_ios:
    # When depending on this package from a real application you should use:
    #   contactos_ios: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  # contactos_platform_interface: ^1.0.0
  contactos_platform_interface:
    path: ../../contactos_platform_interface

  cupertino_icons: any
  collection: any
  intl: any

  permission_handler: ^11.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true
